#!/usr/bin/env python3
"""Build source-checked route specifications; never execute a campaign event."""
import json
from pathlib import Path

from inspect_campaign import REPO, load_npcs, load_stages, parse_tsc, resolve_original_path


DATA = REPO / "runtime/data"
STAGES = {stage.map.lower(): stage for stage in load_stages(DATA, REPO / "runtime/Doukutsu.exe")}
STEPS = []


def step(name, map_name, event, action="interact", **details):
    stage = STAGES[map_name.lower()]
    path = resolve_original_path(DATA / "Stage" / f"{stage.map}.tsc")
    page = parse_tsc(path.read_bytes())
    if event not in page:
        raise ValueError(f"Undefined route observation {map_name}#{event:04}")
    for field in ("result_event", "following_event", "native_death_event", "observed_transfer_event"):
        if field in details and details[field] not in page:
            raise ValueError(f"Undefined route {field} {map_name}#{details[field]:04}")
    for observation in details.get("observed_events", []):
        if observation not in page:
            raise ValueError(f"Undefined route observation {map_name}#{observation:04}")
    npcs = load_npcs(resolve_original_path(DATA / "Stage" / f"{stage.map}.pxe"))
    targets = [{"type": npc["type"], "x": npc["x"] * 16, "y": npc["y"] * 16, "appearance_flag": npc["flag"], "flags": npc["flags"]} for npc in npcs if npc["event"] == event]
    row = {"name": name, "stage": stage.id, "map": stage.map, "observed_event": event, "action": action, "original_targets": targets, **details}
    STEPS.append(row)


def inventory(name, item, observed_event, **details):
    if observed_event not in parse_tsc((DATA / "ArmsItem.tsc").read_bytes()):
        raise ValueError("Undefined original inventory observation")
    STEPS.append({"name": name, "action": "inventory_select_and_use", "item": item, "observed_page": "ArmsItem", "observed_event": observed_event, **details})


def build():
    STEPS.clear()
    step("Enter Egg No. 06", "Eggs", 101, expect_stage=4)
    step("Open ID Card chest", "Egg6", 200, expect_item=7)
    step("Return to Egg Corridor", "Egg6", 100, expect_stage=2)
    step("Enter Egg No. 01", "Eggs", 107, expect_stage=23)
    step("Lower the shield with ID Card", "Egg1", 200, requires_item=7, result_event=201, expect_flags_set=[470])
    step("Return from Egg No. 01", "Egg1", 100, expect_stage=2)
    step("Trigger Igor's encounter", "Eggs", 600, "touch", target_cs=[285 * 16, 2 * 16])
    step("Defeat Igor", "Eggs", 503, "combat", enemy_type=88, requires_real_damage=True, expect_flags_set=[103])
    step("Enter Egg No. 00", "Eggs", 108, result_event=109, expect_stage=3)
    step("Speak to Sue and complete the egg scene", "EggX", 200, dialogue_choice="either", expect_flags_set=[120, 105, 154, 155, 329, 106])
    step("Leave Egg No. 00", "EggX", 100, expect_stage=2)
    step("Return to Arthur's House through teleporter", "Eggs", 100, dialogue_choice="yes", expect_stage=24, note="Original transfer also runs Pens2 700 and Shelter 700; record every stage.")
    step("Finish Sue's network conversation", "Pens2", 700, "advance_dialogue")
    step("Leave Arthur's House to check on Sue", "Pens1", 102, result_event=103, expect_stage=11)
    step("Finish the arrival scene", "Mimi", 400, "advance_dialogue")
    step("Speak to caged Sue", "Mimi", 600, expect_flags_set=[325], expect_teleporter=2)
    step("Enter Arthur's House", "Mimi", 100, expect_stage=1)
    step("Teleport to Grasstown", "Pens1", 500, "interact_and_select", select_teleporter=2, observed_transfer_event=6002, expect_stage=6)
    step("Pick up Santa's Key", "Weed", 200, expect_item=3)
    step("Return the key to Santa", "Weed", 500, expect_flags_set=[212], note="Interact again if initial conversation only describes lost key.")
    step("Enter Santa's House", "Weed", 101, expect_stage=7)
    step("Receive Fireball", "Santa", 500, expect_weapon=3, expect_flags_set=[240, 241])
    step("Leave Santa's House", "Santa", 100, expect_stage=6)
    step("Defeat a Giant Jelly and collect Jellyfish Juice", "Weed", 202, "combat_and_interact", enemy_type=94, expect_item=8, note="Native Giant Jelly death creates its chest; fire actual weapon then open chest.")
    step("Enter Chaco's House", "Weed", 103, expect_stage=8)
    step("Use Juice on Chaco's fireplace", "Chako", 200, requires_item=8, dialogue_choice="yes", result_event=202, expect_stage=6, expect_flags_set=[213])
    step("Talk to Kazuma through the crack", "Weed", 230, dialogue_choice="yes", expect_item=9, expect_flags_set=[215])
    step("Try the rusted door", "Weed", 220, expect_flags_set=[216])
    step("Enter Power Room", "Weed", 104, expect_stage=25)
    step("Switch on the power", "Malco", 200, dialogue_choice="yes", expect_flags_set=[481], result_event=204)
    step("Defeat Power Room Balrog", "Malco", 203, "combat", enemy_type=36, requires_real_damage=True, expect_flags_set=[482], expect_flags_unset=[480])
    step("Pull MALCO out of the floor", "Malco", 300, dialogue_choice="yes", result_event=302, expect_flags_set=[483])
    step("Ask MALCO to make the bomb", "Malco", 300, result_event=304, expect_flags_set=[484])
    step("Leave Power Room", "Malco", 100, expect_stage=6)
    step("Get Gum Key from Kazuma", "Weed", 230, result_event=236, expect_item=10, expect_flags_set=[221])
    step("Collect Juice for Charcoal", "Weed", 202, "combat_and_interact", expect_item=8)
    step("Return to Santa's House", "Weed", 101, expect_stage=7)
    step("Use Juice on Santa's fireplace for Charcoal", "Santa", 300, dialogue_choice="yes", result_event=301, expect_item=12, expect_flags_set=[242])
    step("Leave Santa's House again", "Santa", 100, expect_stage=6)
    step("Collect the final bomb Juice", "Weed", 202, "combat_and_interact", expect_item=8)
    step("Enter Gum with Gum Key", "Weed", 109, requires_item=10, expect_stage=28)
    step("Open Gum Base chest and start Balfrog", "Frog", 200, expect_item=11)
    step("Defeat Balfrog", "Frog", 1000, "combat", boss_number=2, requires_real_damage=True, note="Shoot the open mouth; damage must reach native stage-boss component0.")
    step("Leave Gum", "Frog", 100, expect_stage=6)
    step("Return to MALCO", "Weed", 104, expect_stage=25)
    step("Give MALCO all three materials", "Malco", 300, requires_items=[8, 11, 12], result_event=312, expect_item=13, expect_flags_set=[486])
    step("Leave Power Room with Explosive", "Malco", 100, expect_stage=6)
    step("Use Explosive on Kazuma's door", "Weed", 220, requires_item=13, result_event=250, expect_stage=18, expect_flags_set=[521, 522])
    step("Complete Kazuma's rescue", "Shelt", 200, "advance_dialogue")
    step("Leave Shelter with Kazuma and Professor", "Shelt", 100, result_event=105, expect_stage=6)
    step("Watch Kazuma and Professor leave for the village", "Weed", 600, "advance_dialogue", expect_flags_set=[219, 225])
    step("Return to Arthur's House via the Grasstown teleporter", "Weed", 100, dialogue_choice="yes", expect_stage=1)
    step("Complete Sue's return scene", "Pens1", 620, "advance_dialogue")
    step("Ask Sue about red flowers", "Pens1", 625, expect_flags_set=[158], expect_teleporter=3)
    step("Teleport to Sand Zone", "Pens1", 500, "interact_and_select", select_teleporter=3, observed_transfer_event=6003, expect_stage=10)
    step("Enter Sand Zone Residence", "Sand", 101, expect_stage=29)
    step("Trigger Curly's encounter", "Curly", 300, "touch")
    step("Defeat Curly and deny wanting to kill Mimigas", "Curly", 400, "combat", enemy_type=118, requires_real_damage=True, dialogue_choice="no", result_event=410, expect_flags_set=[562], note="Optional following machine-gun trade can be declined to keep Polar Star.")
    step("Ask the Colons about Jenka and her puppy", "Curly", 200, result_event=206, expect_flags_set=[564])
    step("Enter Curly's Small Room", "Curly", 101, expect_stage=32)
    step("Take the residence puppy", "CurlyS", 400, dialogue_choice="yes", result_event=401, expect_item=14)
    step("Leave the Small Room", "CurlyS", 100, expect_stage=29)
    step("Leave Sand Zone Residence", "Curly", 100, expect_stage=10)
    step("Trigger and defeat Omega", "Sand", 202, "touch_and_combat", boss_number=1, requires_real_damage=True, result_event=210, expect_flags_set=[272])
    step("Enter Jenka's House", "Sand", 103, expect_stage=33)
    step("Return the first puppy", "Jenka1", 200, requires_item=14, expect_flags_set=[590])
    step("Leave Jenka's House", "Jenka1", 100, expect_stage=10)
    step("Take the chest puppy through pawprint passage", "Sand", 412, expect_item=14, note="Original walk-through walls marked with pawprints must retain passability.")
    step("Bring chest puppy to Jenka", "Sand", 103, expect_stage=33)
    step("Return the second puppy", "Jenka1", 200, requires_item=14, expect_flags_set=[591])
    step("Leave Jenka after second puppy", "Jenka1", 100, expect_stage=10)
    step("Enter Deserted House", "Sand", 104, expect_stage=34)
    step("Take Deserted House puppy", "Dark", 400, dialogue_choice="yes", expect_item=14)
    step("Leave Deserted House", "Dark", 100, expect_stage=10)
    step("Bring Deserted House puppy to Jenka", "Sand", 103, expect_stage=33)
    step("Return the third puppy", "Jenka1", 200, requires_item=14, expect_flags_set=[592])
    step("Leave Jenka after third puppy", "Jenka1", 100, expect_stage=10)
    step("Catch the running puppy", "Sand", 402, dialogue_choice="yes", target_cs=[119 * 16, 47 * 16], expect_item=14, note="The actor moves; use its live position.")
    step("Bring running puppy to Jenka", "Sand", 103, expect_stage=33)
    step("Return the fourth puppy", "Jenka1", 200, requires_item=14, expect_flags_set=[593])
    step("Leave Jenka after fourth puppy", "Jenka1", 100, expect_stage=10)
    step("Take sleeping puppy", "Sand", 401, dialogue_choice="yes", expect_item=14)
    step("Carry last puppy across the original trigger", "Sand", 340, "touch", result_event=342, expect_flags_set=[280], note="Trigger at(40,24) requires four returned dogs flag593 and currently carrying flag274.")
    step("Return to Jenka's changed house", "Sand", 103, expect_stage=36)
    step("Complete Balrog's key-theft scene", "Jenka2", 200, "advance_dialogue", expect_flags_set=[278, 595])
    step("Return last puppy to Jenka", "Jenka2", 220, requires_item=14, expect_flags_set=[594, 596])
    step("Leave Jenka's changed house", "Jenka2", 100, expect_stage=10)
    step("Enter Sand Zone Storehouse", "Sand", 230, requires_flags_set=[278], expect_stage=35)
    step("Watch red-flower scene and defeat Frenzied Toroko", "Gard", 502, "advance_and_combat", enemy_type=140, requires_real_damage=True, result_event=503, expect_flags_set=[623])
    step("Speak to the fallen King", "Gard", 505, result_event=600, expect_flags_set=[622])
    step("Accept King's Blade", "Gard", 505, result_event=601, expect_weapon=9)
    step("Leave Storehouse", "Gard", 100, expect_stage=37)
    step("Complete Misery's exile scene", "SandE", 600, "advance_dialogue", expect_stage=9)
    step("Climb Labyrinth I and activate exit panel", "MazeI", 402, dialogue_choice="yes", expect_flags_set=[641])
    step("Use opened Labyrinth I exit", "MazeI", 202, result_event=203, expect_stage=38)
    step("Cross Labyrinth H", "MazeH", 101, expect_stage=39)
    step("Enter Labyrinth Camp", "MazeW", 102, expect_stage=40)
    step("Ask the physician for a cure request", "MazeO", 300, expect_item=17, expect_flags_set=[700])
    step("Return to Labyrinth W", "MazeO", 100, expect_stage=39)
    step("Enter Clinic Ruins", "MazeW", 103, expect_stage=41)
    step("Take Cure-All and defeat Puu Black", "MazeD", 200, "interact_and_combat", enemy_type=160, expect_item=16, requires_real_damage=True)
    step("Leave Clinic Ruins", "MazeD", 100, expect_stage=39)
    step("Return Cure-All at Camp", "MazeW", 102, expect_stage=40)
    step("Give the physician Cure-All", "MazeO", 300, requires_item=16, result_event=302, expect_flags_set=[702])
    step("Leave Camp after Curly recovers", "MazeO", 100, expect_stage=39, expect_flags_set=[704])
    step("Trigger and defeat Monster X", "MazeW", 302, "touch_and_combat", boss_number=3, requires_real_damage=True)
    step("Enter Labyrinth B", "MazeW", 110, expect_stage=43)
    step("Take wounded Professor's Booster v0.8", "MazeB", 501, for_endings=["normal"], expect_item=18, expect_flags_set=[741, 834])
    inventory("Equip Booster v0.8 through original inventory", 18, 6018, for_endings=["normal"], dialogue_choice="yes", expect_equipment_bit=1)
    step("Cross the gap and enter Boulder Chamber", "MazeB", 110, expect_stage=44, note="Best route skips wounded Professor and performs the original long jump.")
    step("Ask Curly about the boulder", "MazeS", 300, expect_flags_set=[761])
    step("Push the boulder from its left side", "MazeS", 320, result_event=321)
    step("Defeat Boulder Chamber Balrog", "MazeS", 310, "combat", enemy_type=169, requires_real_damage=True, result_event=600, expect_flags_set=[764, 781])
    step("Enter Labyrinth M", "MazeS", 110, expect_stage=45)
    step("Traverse Labyrinth M with Curly", "MazeM", 110, expect_stage=46)
    step("Enter the Core room", "Drain", 110, expect_stage=47)
    step("Activate first shutter console", "Almond", 200, dialogue_choice="yes", expect_flags_set=[821, 822])
    step("Clear stuck shutter mechanism", "Almond", 340, "touch", expect_flags_set=[823, 826])
    step("Use first console again to lower lift", "Almond", 200, dialogue_choice="yes", result_event=202, expect_flags_set=[824])
    step("Activate second shutter console", "Almond", 210, dialogue_choice="yes", expect_flags_set=[825])
    step("Pass second shutter trigger", "Almond", 350, "touch", result_event=351, expect_flags_set=[827])
    step("Take the Tow Rope before starting Core", "Almond", 240, for_endings=["best"], requires_flags_unset=[834, 828], dialogue_choice="yes", expect_item=30, expect_flags_set=[839], note="Original rope chest is at tile(71,25); Booster v0.8 flag834 prevents its appearance.")
    step("Investigate the damaged robot with Curly", "Almond", 450, result_event=452, expect_flags_set=[828])
    step("Defeat Core and survive the drowning scene", "Almond", 1000, "combat_and_advance", boss_number=4, requires_real_damage=True, result_event=1110, expect_item=21, expect_equipment_bit=16, expect_flags_set=[830])
    step("Tie the Tow Rope to the unconscious Curly", "Almond", 306, for_endings=["best"], requires_item=30, result_event=307, dialogue_choice="yes", expect_flags_set=[835, 836])
    step("Return through Dark Place", "Almond", 100, expect_stage=46)
    step("Enter waterway grating", "Drain", 121, expect_stage=48)
    step("Enter Waterway Cabin while carrying Curly", "River", 120, for_endings=["best"], requires_flags_set=[836], expect_stage=73)
    step("Rest and lay Curly on the Cabin bed", "Pixel", 250, for_endings=["best"], result_event=251, dialogue_choice="yes", expect_flags_set=[1440], expect_flags_unset=[836])
    step("Read Cabin computer after laying Curly down", "Pixel", 200, for_endings=["best"], result_event=202, expect_flags_set=[1445])
    step("Read notebook and learn how to drain Curly", "Pixel", 221, for_endings=["best"], result_event=222, dialogue_choice="yes", expect_flags_set=[1441])
    step("Drain Curly's water at the bed", "Pixel", 250, for_endings=["best"], result_event=253, dialogue_choice="yes", expect_flags_set=[1442])
    step("Check Curly's reboot at the bed", "Pixel", 250, for_endings=["best"], result_event=254, expect_flags_set=[1443])
    step("Refuse to leave Curly and carry her again", "Pixel", 250, for_endings=["best"], result_event=255, dialogue_choice="no", following_event=256, expect_flags_set=[836, 1444], expect_flags_unset=[1440])
    step("Leave Cabin carrying the drained Curly", "Pixel", 100, for_endings=["best"], expect_stage=48)
    step("Follow currents into Main Artery", "River", 110, "touch", expect_stage=31, conditions_by_ending={"best": {"flags_set": [1444, 836], "flags_unset": [851]}}, note="Best route must visit and finish Cabin before River220 death trigger; passing it while carrying undrained Curly sets irreversible851.")
    step("Defeat Ironhead through original swimming sequence", "Stream", 1000, "combat", boss_number=5, requires_real_damage=True, expect_stage=15, conditions_by_ending={"best": {"result_flags_set": [1042], "result_flags_unset": [836, 851]}})
    step("Leave Reservoir after Core", "Pool", 100, expect_stage=11)
    step("Return to Arthur's House after Core", "Mimi", 100, expect_stage=1)
    step("Watch Professor return and receive Booster v2.0", "Pens1", 651, "touch_and_advance", for_endings=["best"], requires_flags_unset=[834], expect_item=23, expect_flags_set=[744, 162, 741])
    inventory("Equip Booster v2.0 through original inventory", 23, 6023, for_endings=["best"], dialogue_choice="yes", expect_equipment_bit=32)
    step("Read Kazuma's new message", "Pens1", 200)
    step("Teleport to the ruined Egg Corridor", "Pens1", 500, "interact_and_select", select_teleporter=1, observed_transfer_event=6011, expect_stage=49)
    step("Reach Egg No. 00 in ruined corridor", "Eggs2", 108, expect_stage=52)
    step("Read hatching terminal and speak to Kazuma", "EggX2", 500, choices_by_ending={"bad": "yes", "normal": "no", "best": "no"}, expect_flags_set=[940, 941])
    step("Enter Outer Wall", "EggX2", 110, expect_stage=53)
    step("Board Kazuma's Sky Dragon", "Oside", 400, for_endings=["bad"], requires_flags_set=[960], result_event=401, terminal="native narrative wait9999 and song26")
    step("Climb Outer Wall and enter Itoh's Storehouse", "Oside", 120, for_endings=["normal", "best"], expect_stage=55)
    step("Enter Plantation", "Itoh", 110, expect_stage=56)
    step("Enter Rest Area", "Cent", 130, expect_stage=59)
    step("Talk to Mahin before he leaves", "Lounge", 250, expect_flags_set=[1021])
    step("Leave Rest Area", "Lounge", 100, expect_stage=56)
    step("Ask Kanpachi about his strange catch", "Cent", 260, expect_flags_set=[1035])
    step("Look in Kanpachi's bucket", "Cent", 265, result_event=266, expect_item=25, expect_flags_set=[1022])
    step("Unlock Plantation teleporter room", "Cent", 135, requires_item=25, result_event=136, expect_stage=60, expect_flags_set=[1023])
    step("Attempt teleporter and be captured", "CentW", 150, dialogue_choice="yes", expect_stage=57, expect_item=26)
    step("Speak to imprisoned Mahin", "Jail1", 200, expect_flags_set=[1080])
    step("Leave Jail No. 1", "Jail1", 100, expect_stage=56)
    inventory("Read Sue's Letter through normal inventory", 26, 6026, dialogue_choice="yes", expect_flags_set=[1024])
    step("Speak to amnesiac Curly in the Plantation spring", "Cent", 320, for_endings=["best"], expect_flags_set=[1041])
    step("Ask Cthulhu about Curly's lost memories", "Cent", 310, for_endings=["best"], requires_flags_set=[1041], result_event=311, expect_flags_set=[1044])
    step("Reenter unlocked Plantation teleporter room", "Cent", 135, for_endings=["best"], result_event=137, expect_stage=60)
    step("Use teleporter after the capture has already occurred", "CentW", 150, for_endings=["best"], requires_flags_set=[1140], result_event=152, dialogue_choice="yes", expect_stage=1)
    step("Leave Arthur's House for Ma Pignon", "Pens1", 102, for_endings=["best"], expect_stage=11)
    step("Enter Mimiga Graveyard", "Mimi", 104, for_endings=["best"], result_event=112, expect_stage=16)
    step("Enter Graveyard Storage", "Cemet", 110, for_endings=["best"], expect_stage=83)
    step("Ask Ma Pignon about amnesia and the badge", "Mapi", 400, for_endings=["best"], requires_flags_set=[1044], dialogue_choices=["yes", "yes", "no", "yes", "yes", "no"], observed_events=[402, 403, 404, 405, 406, 407, 410], expect_item=33, expect_flags_set=[1561, 1562], note="Choices are: business yes, want badge yes, really do not want no, want that much yes, absolutely positively yes, really do not want no.")
    inventory("Read Mushroom Badge to expose the trick", 33, 6033, for_endings=["best"], expect_flags_set=[1563])
    step("Confront Ma Pignon and defeat him", "Mapi", 400, "interact_and_combat", for_endings=["best"], result_event=420, enemy_type=313, requires_real_damage=True, native_death_event=500, expect_item=34)
    step("Leave Graveyard Storage", "Mapi", 100, for_endings=["best"], expect_stage=16)
    step("Leave Mimiga Graveyard", "Cemet", 100, for_endings=["best"], expect_stage=11)
    step("Return to Arthur's House with Ma Pignon", "Mimi", 100, for_endings=["best"], expect_stage=1)
    step("Teleport back to Plantation", "Pens1", 500, "interact_and_select", for_endings=["best"], select_teleporter=5, observed_transfer_event=6005, expect_stage=60)
    step("Exit Plantation teleporter room", "CentW", 100, for_endings=["best"], expect_stage=56)
    step("Feed Ma Pignon to Curly", "Cent", 320, for_endings=["best"], requires_item=34, result_event=322, dialogue_choice="yes", expect_flags_set=[1045])
    step("Speak to Curly again and receive Iron Bond", "Cent", 320, for_endings=["best"], result_event=324, expect_item=39, expect_flags_set=[1046])
    step("Speak the Hideout password", "Cent", 120, requires_flags_set=[1024], result_event=121, expect_stage=58)
    step("Help Momorin build the rocket", "Momo", 200, dialogue_choice="no", result_event=205, expect_item=24, expect_equipment_bit=64, expect_flags_set=[1101, 1020])
    step("Leave Hideout disguised as a Mimiga", "Momo", 100, expect_stage=56)
    step("Find the broken sprinkler", "Cent", 415, result_event=416, expect_item=28, note="Actor at(15,69); shootable ordinary enemies remain active while masked.")
    step("Enter Rest Area with Broken Sprinkler", "Cent", 130, expect_stage=59)
    step("Trade Broken Sprinkler for working Sprinkler", "Lounge", 200, requires_item=28, result_event=202, expect_item=29)
    step("Leave Rest Area with Sprinkler", "Lounge", 100, expect_stage=56)
    step("Return to Momorin", "Cent", 120, expect_stage=58)
    step("Give Momorin the working Sprinkler", "Momo", 200, requires_item=29, result_event=210, expect_flags_set=[1102])
    step("Leave Hideout for Itoh's Controller", "Momo", 100, expect_stage=56)
    step("Return to Itoh's Storehouse", "Cent", 100, expect_stage=55)
    step("Ask Itoh for Controller", "Itoh", 400, requires_flags_set=[1102], result_event=403, expect_item=27)
    step("Return to Plantation with Controller", "Itoh", 110, expect_stage=56)
    step("Return to Hideout with Controller", "Cent", 120, expect_stage=58)
    step("Give Momorin the Controller", "Momo", 200, requires_item=27, result_event=211, expect_flags_set=[1103])
    step("Sleep while rocket is completed", "Momo", 280, dialogue_choice="yes", result_event=281, expect_flags_set=[1030, 1031, 1032, 1033, 1105])
    step("Leave the completed rocket Hideout", "Momo", 100, expect_stage=56)
    step("Receive Booster back and return Mimiga Mask", "Cent", 370, expect_flags_set=[1034], expect_flags_unset=[1020], note="Original flag162 chooses Booster v2.0; otherwise v0.8.")
    inventory("Equip returned Booster v0.8", 18, 6018, for_endings=["normal"], dialogue_choice="yes", expect_equipment_bit=1)
    inventory("Equip returned Booster v2.0", 23, 6023, for_endings=["best"], dialogue_choice="yes", expect_equipment_bit=32)
    step("Ride the rocket to Final Cave entrance", "Cent", 350, "interact_and_ride", requires_flags_set=[1030], note="Native moving platform must carry actual Terraria avatar to tile(80,9).")
    step("Enter Final Cave", "Cent", 150, result_event=151, expect_stage=63, for_endings=["normal"])
    step("Traverse Final Cave and reach Balcony", "Priso1", 110, for_endings=["normal"], expect_stage=62)
    step("Enter Final Cave Hidden with Booster v2.0", "Cent", 150, for_endings=["best"], result_event=151, following_event=160, requires_item=23, expect_stage=67, note="All weapon experience is removed by the original hidden-cave entry event; keep native progression.")
    step("Trigger and defeat Red Demon in Hidden Final Cave", "Priso2", 241, "touch_and_combat", for_endings=["best"], enemy_type=276, requires_real_damage=True, native_death_event=250)
    step("Traverse Hidden Final Cave and reach Balcony", "Priso2", 110, for_endings=["best"], expect_stage=62)
    step("Enter Throne Room", "Blcny1", 110, "touch", expect_stage=64)
    step("Trigger and defeat Misery", "Ring1", 500, "touch_and_combat", enemy_type=247, requires_real_damage=True, result_event=400)
    step("Enter The King's Table", "Ring1", 110, expect_stage=65)
    step("Trigger Doctor battle", "Ring2", 500, "touch", result_event=502)
    step("Defeat Doctor's first form", "Ring2", 410, "combat", enemy_type=263, requires_real_damage=True)
    step("Defeat Frenzied Doctor", "Ring2", 420, "combat", enemy_type=267, requires_real_damage=True)
    step("Enter Black Space", "Ring2", 110, expect_stage=68)
    step("Trigger Undead Core confrontation", "Ring3", 500, "touch", result_event=502)
    step("Defeat Undead Core", "Ring3", 1000, "combat", boss_number=7, requires_real_damage=True, expect_flags_set=[1340], expect_stage=70)
    step("Complete escape quake scene", "Blcny2", 300, "advance_dialogue", note="The original scene returns to Ring3 600 before releasing the player.")
    step("Escape through Throne Room", "Ring3", 100, expect_stage=65)
    step("Escape The King's Table", "Ring2", 100, expect_stage=64)
    step("Follow Sue back to collapsing Balcony", "Ring1", 100, expect_stage=70)
    step("Escape the falling island", "Blcny2", 400, "touch_and_advance", for_endings=["normal"], note="Sue's jump/escape carries the authored cutscene through Eggs2, Weed, MazeW, Almond, Cent and Island100; retain scripted movement/camera.")
    step("Finish Island destruction cinematic", "Island", 100, "advance_dialogue", for_endings=["normal"], expect_stage=71)
    step("Finish Kazuma rescue scene", "Fall", 100, "advance_dialogue", for_endings=["normal"], expect_stage=0)
    step("Let original credits finish", "0", 100, "wait_original_credits", for_endings=["normal"], terminal="stage0 actor360 THANK YOU and native event1100 WaitTicks(...,9999) infinite hold; credits startup alone is insufficient")
    step("Enter the reopened Prefab Building on collapsing Balcony", "Blcny2", 121, for_endings=["best"], requires_flags_set=[1393, 1046], requires_item=23, expect_stage=79, note="Ring3 original victory event1002 sets1393 only when Booster v2.0 and Iron Bond conditions hold.")
    step("Descend Prefab hole into Sacred Ground", "Prefa2", 110, "touch", for_endings=["best"], expect_stage=80)
    step("Attach Curly with the Tow Rope in Sacred Ground", "Hell1", 500, for_endings=["best"], expect_flags_set=[1532], expect_flags_unset=[1531])
    step("Traverse Sacred Ground B1", "Hell1", 110, "touch", for_endings=["best"], expect_stage=81)
    step("Traverse Sacred Ground B2", "Hell2", 110, "touch", for_endings=["best"], expect_stage=82)
    step("Trigger Heavy Press at the end of Sacred Ground B3", "Hell3", 300, "touch", for_endings=["best"], boss_number=8)
    step("Defeat Heavy Press and let it fall through the floor", "Hell3", 1000, "combat", for_endings=["best"], boss_number=8, requires_real_damage=True, expect_flags_set=[1534], note="Native Heavy Press sets1534 while falling; its physical fall and CMP floor openings must remain active.")
    step("Follow Heavy Press into the opened passage", "Hell3", 110, "touch", for_endings=["best"], requires_flags_set=[1534], result_event=111, expect_stage=85)
    step("Enter the Seal Chamber corridor", "Hell42", 130, for_endings=["best"], expect_stage=88)
    step("Enter the Seal Chamber", "Ostep", 110, for_endings=["best"], expect_stage=87)
    step("Hear Ballos and begin his human-form battle", "Ballo1", 500, "touch_and_advance", for_endings=["best"])
    step("Defeat human Ballos", "Ballo1", 900, "combat", for_endings=["best"], enemy_type=340, requires_real_damage=True, note="Human actor death starts original stage boss9; this is an observed death event.")
    step("Defeat Ballos's next form", "Ballo1", 1000, "combat", for_endings=["best"], boss_number=9, requires_real_damage=True, expect_flags_set=[1600])
    step("Defeat Ballos's final forms", "Ballo1", 1001, "combat", for_endings=["best"], boss_number=9, requires_real_damage=True, expect_stage=91)
    step("Watch the island survive", "Island", 110, "advance_dialogue", for_endings=["best"], expect_stage=92)
    step("Complete Balrog's rescue of Quote and Curly", "Ballo2", 500, "advance_dialogue", for_endings=["best"], expect_stage=71)
    step("Finish the best ending's flight conversation", "Fall", 120, "advance_dialogue", for_endings=["best"], expect_flags_set=[2000, 1460], expect_stage=0)
    step("Let original best ending credits finish", "0", 100, "wait_original_credits", for_endings=["best"], terminal="stage0 actor360 THANK YOU and native event1200 WaitTicks(...,9999) infinite hold; credits startup alone is insufficient")
    return {"scope": "Source-checked waypoint/gate specification. IDs are observations only; no event calls, flags, warps or direct damage are commands.", "includes": ["early_route.json"], "default_ending": "normal", "steps": list(STEPS)}


def select_ending(route, ending):
    selected = []
    for row in route["steps"]:
        if ending in row.get("for_endings", ["bad", "normal", "best"]):
            selected.append(row)
        if ending == "bad" and row.get("terminal"):
            break
    return {**route, "selected_ending": ending, "steps": selected}


if __name__ == "__main__":
    path = Path(__file__).with_name("main_story_route.json")
    route = build()
    path.write_text(json.dumps(route, indent=2) + "\n")
    print(f"Wrote {len(route['steps'])} source-checked route steps to {path}")
    for ending in ("bad", "normal", "best"):
        selected = select_ending(route, ending)
        output = path.with_name(f"{ending}_route.json")
        output.write_text(json.dumps(selected, indent=2) + "\n")
        print(f"Wrote {len(selected['steps'])} {ending} route steps to {output}")
